disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "DHangaard"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"
copyright = "© { year } DHangaard"

[[params.author.links]]
github = "https://github.com/DHangaard"

[[params.author.links]]
linkedin = "www.linkedin.com/in/dhangaard"

["params.author"]
name = "DHangaard"
image = "profilePicGB.png"
headline = "Studying AP in Computer Science"
