[[main]]
name = "Blog"
weight = 10

[[main]]
name = "Posts"
parent = "Blog"
pageRef = "posts"
weight = 11

[[main]]
name = "Categories"
parent = "Blog"
pageRef = "categories"
weight = 12

[[main]]
name = "Tags"
parent = "Blog"
pageRef = "tags"
weight = 13

[[main]]
name = "Projects"
pageRef = "projects"
weight = 20

[[main]]
name = "About"
pageRef = "about"
weight = 30

[[footer]]
none = "none"
